Repository ismaelsadeeq/Data-Structures-Algorithms-Problems, pull requests merged in 2022-10, with the labels that each got.

#1 added algorithm explanation of linear search
  Search/Python-Search/LinearSearch.md
Labels: hacktoberfest-accepted

#6 Issue 3 - Quicksort - Java
  sorting/QuickSortJava/Quicksort.java
  sorting/QuickSortJava/ReadMe.md
Labels: hacktoberfest-accepted

#10 TOH using Recursion
  Recursion/CppTowerOfHanoi/ReadMe.md
  Recursion/CppTowerOfHanoi/TowerofHanoi.cpp
Labels: hacktoberfest-accepted

#12 Recursion
  Recursion/C-Prime-Number/PrimeNumber.c
  Recursion/C-Prime-Number/ReadMe.md
Labels: hacktoberfest-accepted, hacktoberfest

#21 Bubble Sort in Java
  Sorting/Java/BubbleSort.java
Labels: hacktoberfest-accepted, hacktoberfest

#27 Fix typos in README.md and CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation, hacktoberfest-accepted

#29 Added MergeSort and BubbleSort using Javascript
  Sorting/JavaScript/BubbleSort/BubbleSort.js
  Sorting/JavaScript/BubbleSort/ReadMe.md
  Sorting/JavaScript/MergeSort/MergeSort.js
  Sorting/JavaScript/MergeSort/ReadMe.md
Labels: hacktoberfest-accepted, hacktoberfest

#39 Implemented merge-overlapping-intervals with python
  Array/Python/FibonacciNumber/NthFibonacciNumber.py
  Array/Python/FibonacciNumber/Readme.md
  Array/Python/MergeOverlappingIntervals/MergeOverlappingIntervals.py
  Array/Python/MergeOverlappingIntervals/ReadMe.md
Labels: hacktoberfest-accepted

#42 container with most water
  TwoPointer/Python/ContainerWithMaximumWater/ContainerWithMaximumWater.py
  TwoPointer/Python/ContainerWithMaximumWater/ReadMe.md
Labels: hacktoberfest-accepted, hacktoberfest

#54 Implement Stack Data Structure with Its Operations Using Array
  Stack/Array/C/ReadMe.md
  Stack/Array/C/Stack.c
  Stack/Array/C/Stack.h
Labels: hacktoberfest-accepted

#55 added moore-voting-algorithm
  Moore-Voting-Algorithm/Dart/MooreVotingAlgorithm.dart
  Moore-Voting-Algorithm/Dart/README.md
Labels: hacktoberfest-accepted

#57 added interpolation search 🚀
  Search/Dart/Interpolation-Search/InterpolationSearch.dart
  Search/Dart/Interpolation-Search/README.md
Labels: hacktoberfest-accepted

#56 ⚡ added squared sorted array 🚀
  Array/Dart/Sorted-Squared-Array/README.md
  Array/Dart/Sorted-Squared-Array/SortedSquaredArray.dart
Labels: hacktoberfest-accepted

#58 implement AVL Tree in JavaScript
  AVLTree/JavaScript/AVLTree.js
  AVLTree/JavaScript/ReadMe.md
Labels: hacktoberfest-accepted
